# Exported from Render on 2025-04-08T02:12:34Z
services:
  - type: web
    name: blog_forum
    runtime: docker
    repo: https://github.com/NPimtrll/blog_forum
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: WEB_CONCURRENCY
        value: "2"
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true

version: "1"
