# Exported from Render on 2025-04-08T02:12:34Z
services:
  - type: web
    name: blog_forum
    runtime: docker
    repo: https://github.com/NPimtrll/blog_forum
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
version: "1"
