services:
  - type: web
    name: blog-forum
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-forum-db
          property: connectionString
    plan: free

databases:
  - name: blog-forum-db
    databaseName: blog_forum_production
    user: blog_forum
    plan: free
